#!/usr/bin/env bash
set -euo pipefail
#===============================================================================
# cleanup.sh — Cleanup Mininet environment and temporary files
#===============================================================================
# usage: ./scripts/cleanup.sh [--all|--mininet|--temp|--pcap]
#===============================================================================

set -euo pipefail

# Culori
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARN]${NC} $1"; }

#-------------------------------------------------------------------------------
# Cleaning Mininet
#-------------------------------------------------------------------------------

cleanup_mininet() {
    log_info "Cleaning Mininet..."
    
    # Stop Mininet processes
    if pgrep -f "mininet" > /dev/null 2>&1; then
        sudo pkill -f "mininet" 2>/dev/null || true
    fi
    
    # Standard Mininet cleanup
    if command -v mn &> /dev/null; then
        sudo mn -c 2>/dev/null || true
        log_success "Mininet cleanup executed"
    else
        log_warning "mn command is not available"
    fi
    
    # Clean remaining virtual interfaces
    for intf in $(ip link show 2>/dev/null | grep -oE "(s[0-9]+-eth[0-9]+|h[0-9]+-eth[0-9]+|r[0-9]+-eth[0-9]+)" | sort -u); do
        sudo ip link delete "$intf" 2>/dev/null || true
    done
    
    # Clean network namespaces
    for ns in $(ip netns list 2>/dev/null | awk '{print $1}'); do
        if [[ "$ns" =~ ^(h[0-9]+|r[0-9]+|s[0-9]+)$ ]]; then
            sudo ip netns delete "$ns" 2>/dev/null || true
        fi
    done
    
    # Restart Open vSwitch (if needed)
    if systemctl is-active --quiet openvswitch-switch 2>/dev/null; then
        sudo systemctl restart openvswitch-switch
        log_success "Open vSwitch restarted"
    fi
}

#-------------------------------------------------------------------------------
# Cleaning temporary files
#-------------------------------------------------------------------------------

cleanup_temp() {
    log_info "Cleaning temporary files..."
    
    # Python cache
    find "$PROJECT_ROOT" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    find "$PROJECT_ROOT" -type f -name "*.pyc" -delete 2>/dev/null || true
    find "$PROJECT_ROOT" -type f -name "*.pyo" -delete 2>/dev/null || true
    
    # Editor files
    find "$PROJECT_ROOT" -type f -name "*~" -delete 2>/dev/null || true
    find "$PROJECT_ROOT" -type f -name "*.swp" -delete 2>/dev/null || true
    find "$PROJECT_ROOT" -type f -name "*.swo" -delete 2>/dev/null || true
    
    # Temporary logs
    find "$PROJECT_ROOT" -type f -name "*.log" -mtime +7 -delete 2>/dev/null || true
    
    # Temporary JSON generated by scripts
    rm -f "$PROJECT_ROOT"/python/exercises/*.json 2>/dev/null || true
    
    log_success "Temporary files cleaned"
}

#-------------------------------------------------------------------------------
# Cleaning PCAP captures
#-------------------------------------------------------------------------------

cleanup_pcap() {
    log_info "Cleaning PCAP captures..."
    
    if [[ -d "$PROJECT_ROOT/pcap" ]]; then
        # Keep only files smaller than 1MB and from the last 7 days
        find "$PROJECT_ROOT/pcap" -type f -name "*.pcap" -size +1M -delete 2>/dev/null || true
        find "$PROJECT_ROOT/pcap" -type f -name "*.pcap" -mtime +7 -delete 2>/dev/null || true
        log_success "Large/old PCAP captures deleted"
    fi
    
    # Clean from /tmp
    sudo rm -f /tmp/*.pcap 2>/dev/null || true
}

#-------------------------------------------------------------------------------
# Complete cleanup
#-------------------------------------------------------------------------------

cleanup_all() {
    cleanup_mininet
    cleanup_temp
    cleanup_pcap
    log_success "Complete cleanup finished!"
}

#-------------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------

main() {
    echo ""
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║              Cleanup Starterkit Week 5                  ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo ""
    
    local mode="${1:---all}"
    
    case "$mode" in
        --all)
            cleanup_all
            ;;
        --mininet)
            cleanup_mininet
            ;;
        --temp)
            cleanup_temp
            ;;
        --pcap)
            cleanup_pcap
            ;;
        --help|-h)
            echo "usage: $0 [--all|--mininet|--temp|--pcap]"
            echo ""
            echo "Options:"
            echo "  --all      Complete cleanup (implicit)"
            echo "  --mininet  Mininet cleanup only"
            echo "  --temp     Temporary files only"
            echo "  --pcap     Old/large PCAP captures only"
            ;;
        *)
            echo "Unknown option: $mode"
            exit 1
            ;;
    esac
}

main "$@"
