#!/bin/bash
# =============================================================================
# smoke_test.sh – Artefact and functionality verification WEEK 11
# =============================================================================
# Verifies:
#   1. Existence of artefacts (demo.log, demo.pcap, validation.txt)
#   2. Minimum content of each artefact
#   3. Python script syntax
#   4. Docker Compose configurations
# =============================================================================
# Usage: ./smoke_test.sh
# Exit codes: 0 = success, >0 = number of errors
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ARTIFACTS_DIR="$ROOT_DIR/artifacts"

# Colours
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

ERRORS=0
WARNINGS=0

# ─────────────────────────────────────────────────────────────────────────────
# Helper functions
# ─────────────────────────────────────────────────────────────────────────────

pass() {
    echo -e "${GREEN}[✓]${NC} $1"
}

fail() {
    echo -e "${RED}[✗]${NC} $1"
    ERRORS=$((ERRORS + 1))
}

warn() {
    echo -e "${YELLOW}[!]${NC} $1"
    WARNINGS=$((WARNINGS + 1))
}

info() {
    echo -e "${BLUE}[i]${NC} $1"
}

# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Smoke Test – Week 11${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# 1. Artefact existence verification
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${YELLOW}─── 1. Artefact verification ───${NC}"

if [[ -d "$ARTIFACTS_DIR" ]]; then
    pass "Directory artifacts/ exists"
else
    fail "Directory artifacts/ missing"
fi

# demo.log
if [[ -f "$ARTIFACTS_DIR/demo.log" ]]; then
    SIZE=$(stat -f%z "$ARTIFACTS_DIR/demo.log" 2>/dev/null || stat -c%s "$ARTIFACTS_DIR/demo.log" 2>/dev/null || echo "0")
    if [[ "$SIZE" -gt 100 ]]; then
        pass "demo.log exists and has content ($SIZE bytes)"
    else
        warn "demo.log exists but is too small ($SIZE bytes)"
    fi
else
    warn "demo.log not present yet (run: make run-all)"
fi

# demo.pcap
if [[ -f "$ARTIFACTS_DIR/demo.pcap" ]]; then
    SIZE=$(stat -f%z "$ARTIFACTS_DIR/demo.pcap" 2>/dev/null || stat -c%s "$ARTIFACTS_DIR/demo.pcap" 2>/dev/null || echo "0")
    if [[ "$SIZE" -gt 0 ]]; then
        pass "demo.pcap exists ($SIZE bytes)"
    else
        warn "demo.pcap exists but is empty (capture requires tshark/tcpdump)"
    fi
else
    warn "demo.pcap not present yet (optional, generated by make run-all or make capture)"
fi

# validation.txt
if [[ -f "$ARTIFACTS_DIR/validation.txt" ]]; then
    if grep -q "PASS" "$ARTIFACTS_DIR/validation.txt" 2>/dev/null; then
        PASS_COUNT=$(grep -c "PASS" "$ARTIFACTS_DIR/validation.txt" 2>/dev/null || echo "0")
        pass "validation.txt contains $PASS_COUNT PASS checks"
    else
        warn "validation.txt exists but contains no PASS checks"
    fi
else
    warn "validation.txt not present yet (run: make run-all)"
fi

echo ""

# ─────────────────────────────────────────────────────────────────────────────
# 2. Python syntax verification
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${YELLOW}─── 2. Python syntax verification ───${NC}"

PYTHON_FILES=(
    "python/exercises/ex_11_01_backend.py"
    "python/exercises/ex_11_02_loadbalancer.py"
    "python/exercises/ex_11_03_dns_client.py"
    "python/utils/net_utils.py"
)

for pf in "${PYTHON_FILES[@]}"; do
    FULL_PATH="$ROOT_DIR/$pf"
    if [[ -f "$FULL_PATH" ]]; then
        if python3 -m py_compile "$FULL_PATH" 2>/dev/null; then
            pass "$pf"
        else
            fail "$pf (syntax error)"
        fi
    else
        warn "$pf does not exist"
    fi
done

echo ""

# ─────────────────────────────────────────────────────────────────────────────
# 3. Docker configuration verification
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${YELLOW}─── 3. Docker Compose verification ───${NC}"

COMPOSE_FILES=(
    "docker/nginx_compose/docker-compose.yml"
    "docker/custom_lb_compose/docker-compose.yml"
    "docker/dns_demo/docker-compose.yml"
    "docker/ftp_demo/docker-compose.yml"
    "docker/ssh_demo/docker-compose.yml"
)

for cf in "${COMPOSE_FILES[@]}"; do
    FULL_PATH="$ROOT_DIR/$cf"
    if [[ -f "$FULL_PATH" ]]; then
        if command -v docker &> /dev/null; then
            if docker compose -f "$FULL_PATH" config > /dev/null 2>&1; then
                pass "$cf"
            else
                # Try without validation (might not have docker running)
                if grep -q "services:" "$FULL_PATH" 2>/dev/null; then
                    pass "$cf (structure valid)"
                else
                    fail "$cf (invalid)"
                fi
            fi
        else
            if grep -q "services:" "$FULL_PATH" 2>/dev/null; then
                pass "$cf (docker not available, basic check)"
            else
                fail "$cf (missing services section)"
            fi
        fi
    else
        warn "$cf does not exist"
    fi
done

echo ""

# ─────────────────────────────────────────────────────────────────────────────
# 4. Script verification
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${YELLOW}─── 4. Shell script verification ───${NC}"

SCRIPTS=(
    "scripts/setup.sh"
    "scripts/run_all.sh"
    "scripts/cleanup.sh"
    "scripts/verify.sh"
)

for sc in "${SCRIPTS[@]}"; do
    FULL_PATH="$ROOT_DIR/$sc"
    if [[ -f "$FULL_PATH" ]]; then
        if bash -n "$FULL_PATH" 2>/dev/null; then
            pass "$sc"
        else
            fail "$sc (bash syntax error)"
        fi
    else
        fail "$sc does not exist"
    fi
done

echo ""

# ─────────────────────────────────────────────────────────────────────────────
# 5. Mininet verification (optional)
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${YELLOW}─── 5. Mininet topologies verification ───${NC}"

MININET_FILES=(
    "mininet/topologies/topo_11_base.py"
    "mininet/topologies/topo_11_extended.py"
)

for mf in "${MININET_FILES[@]}"; do
    FULL_PATH="$ROOT_DIR/$mf"
    if [[ -f "$FULL_PATH" ]]; then
        if python3 -m py_compile "$FULL_PATH" 2>/dev/null; then
            pass "$mf"
        else
            fail "$mf (syntax error)"
        fi
    else
        warn "$mf does not exist"
    fi
done

echo ""

# ─────────────────────────────────────────────────────────────────────────────
# 6. README and documentation verification
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${YELLOW}─── 6. Documentation verification ───${NC}"

DOC_FILES=(
    "README.md"
    "docs/lab.md"
    "docs/seminar.md"
    "docs/curs.md"
)

for df in "${DOC_FILES[@]}"; do
    FULL_PATH="$ROOT_DIR/$df"
    if [[ -f "$FULL_PATH" ]]; then
        SIZE=$(stat -f%z "$FULL_PATH" 2>/dev/null || stat -c%s "$FULL_PATH" 2>/dev/null || echo "0")
        if [[ "$SIZE" -gt 500 ]]; then
            pass "$df ($SIZE bytes)"
        else
            warn "$df exists but is short ($SIZE bytes)"
        fi
    else
        fail "$df does not exist"
    fi
done

echo ""

# ─────────────────────────────────────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"

if [[ $ERRORS -eq 0 ]]; then
    if [[ $WARNINGS -eq 0 ]]; then
        echo -e "${GREEN}  SUCCESS: All checks passed! ✓${NC}"
    else
        echo -e "${YELLOW}  SUCCESS with warnings: $WARNINGS warning(s)${NC}"
    fi
else
    echo -e "${RED}  FAILURE: $ERRORS errors, $WARNINGS warnings${NC}"
fi

echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo ""

# Display artefacts summary
if [[ -d "$ARTIFACTS_DIR" ]]; then
    info "Artefacts in $ARTIFACTS_DIR/:"
    ls -la "$ARTIFACTS_DIR/" 2>/dev/null | grep -v "^total" | grep -v "^d" || true
fi

echo ""

exit $ERRORS

# Revolvix&Hypotheticalandrei
